/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as autoMineSol from "./AutoMine.sol";
export type { autoMineSol };
import type * as mocks from "./mocks";
export type { mocks };
