/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutoMine } from "./AutoMine";
export type { IDigDragonMine } from "./IDigDragonMine";
export type { IHashPowerStorage } from "./IHashPowerStorage";
