/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockDigDragonMine } from "./MockDigDragonMine";
export type { MockERC721 } from "./MockERC721";
export type { MockHashPowerStorage } from "./MockHashPowerStorage";
