/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDigDragonMine,
  IDigDragonMineInterface,
} from "../../../contracts/AutoMine.sol/IDigDragonMine";

const _abi = [
  {
    inputs: [],
    name: "earnReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_miner",
        type: "address",
      },
    ],
    name: "pendingReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenIds",
        type: "uint256[]",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenIds",
        type: "uint256[]",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDigDragonMine__factory {
  static readonly abi = _abi;
  static createInterface(): IDigDragonMineInterface {
    return new Interface(_abi) as IDigDragonMineInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDigDragonMine {
    return new Contract(address, _abi, runner) as unknown as IDigDragonMine;
  }
}
