/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHashPowerStorage,
  IHashPowerStorageInterface,
} from "../../../contracts/AutoMine.sol/IHashPowerStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getHashPower",
    outputs: [
      {
        internalType: "uint256",
        name: "power",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHashPowerStorage__factory {
  static readonly abi = _abi;
  static createInterface(): IHashPowerStorageInterface {
    return new Interface(_abi) as IHashPowerStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHashPowerStorage {
    return new Contract(address, _abi, runner) as unknown as IHashPowerStorage;
  }
}
