/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AutoMine__factory } from "./AutoMine__factory";
export { IDigDragonMine__factory } from "./IDigDragonMine__factory";
export { IHashPowerStorage__factory } from "./IHashPowerStorage__factory";
